### ISSUE TITLE
How to get the OSInfo.OsVersion enum for the current machine

### ISSUE THREAD

**Issue by jonreis** [anjdreas/OsInfo#2]
Hello Anjdres,

thank you for making this library available.

I'm probably missing something, but want I want is to get the OSInfo.OsVersion enum for the local machine. Something like: 

public static OsVersion GetOsVersionInfo(this OperatingSystem os)

I need this so I can do something like:

        if (os == OsVersion.WinServer2008 || os == OsVersion.WinServer2008R2)
          topOffset = -3;

Does this exist?

Better yet, maybe make OsVersionInfo public and provide

public static OsVersionInfo GetOsVersionInfo(this OperatingSystem os)

Just a thought

**Comment by angularsen** [comment]
Hi, I think you want this one to be public?

https://github.com/anjdreas/OsInfo/blob/master/OsInfo/src/Extensions/OperatingSystemExtensions.cs#L134

Then you can do `Environment.OsVersion.GetOsVersionInfo().OsVersion == OsVersion.WinServer2008`.

**Comment by angularsen** [comment]
It's been a long while since I touched this repo, but I'll see if I can find time to do this and release a new nuget in a few days.

**Comment by jonreis** [comment]
Hi Anjdreas,

no worries. I thought the repo was still active. I can manage without the change.

Thank you for offering.

Best Regards,
Jonathan

**Comment by angularsen** [comment]
So I actually tried doing this, and realized you cannot unambiguously resolve the `OsVersion` enum value for an `OperatingSystem`, because that type simply does not hold enough information to distinguish between workstation and server editions, such as `Win7` vs `Win2008Server`, `Win8` vs `WinServer2012` etc.

Here is the full list, as you can see there are overlapping versions only differentiated by `OsProductType.Server` and `.Workstation`. These are our constructs and does not really matter when you are comparing less/equal/greater than on versions.

```csharp
        static OperatingSystemExtensions()
        {
            Versions = new[]
            {
                new OsVersionInfo(OsVersion.Win32S, PlatformID.Win32S, 0, 0),
                new OsVersionInfo(OsVersion.Win95, PlatformID.Win32Windows, 4, 0),
                new OsVersionInfo(OsVersion.Win98, PlatformID.Win32Windows, 4, 10),
                new OsVersionInfo(OsVersion.WinME, PlatformID.Win32Windows, 4, 90),
                new OsVersionInfo(OsVersion.WinNT351, PlatformID.Win32NT, 3, 51),
                new OsVersionInfo(OsVersion.WinNT4, PlatformID.Win32NT, 4, 0),
                new OsVersionInfo(OsVersion.Win2000, PlatformID.Win32NT, 5, 0),
                new OsVersionInfo(OsVersion.WinXP, PlatformID.Win32NT, 5, 1),
                new OsVersionInfo(OsVersion.Win2003, PlatformID.Win32NT, 5, 2, OsProductType.Server),
                new OsVersionInfo(OsVersion.WinXPx64, PlatformID.Win32NT, 5, 2, OsProductType.Workstation),
                new OsVersionInfo(OsVersion.Vista, PlatformID.Win32NT, 6, 0, OsProductType.Workstation),
                new OsVersionInfo(OsVersion.WinServer2008, PlatformID.Win32NT, 6, 0, OsProductType.Server),
                new OsVersionInfo(OsVersion.WinServer2008R2, PlatformID.Win32NT, 6, 1, OsProductType.Server),
                new OsVersionInfo(OsVersion.Win7, PlatformID.Win32NT, 6, 1, OsProductType.Workstation),
                new OsVersionInfo(OsVersion.WinServer2012, PlatformID.Win32NT, 6, 2, OsProductType.Server),
                new OsVersionInfo(OsVersion.Win8, PlatformID.Win32NT, 6, 2, OsProductType.Workstation),
                new OsVersionInfo(OsVersion.WinServer2012R2, PlatformID.Win32NT, 6, 3, OsProductType.Server),
                new OsVersionInfo(OsVersion.Win8Update1, PlatformID.Win32NT, 6, 3, OsProductType.Workstation),
                new OsVersionInfo(OsVersion.Win10, PlatformID.Win32NT, 10, 0, OsProductType.Workstation)
            };
        }
```

A dump of my local machine's `OperatingSystem` gives the following, which highlights I simply cannot distinguish between Win10 Home/Pro and Win Server 2016. They are the same versions.
![image](https://cloud.githubusercontent.com/assets/787816/21441781/30ec0baa-c89a-11e6-8083-0f89b2e219fb.png)

The only way to achieve this is to query the windows API or possibly the registry:
http://stackoverflow.com/questions/30520741/c-sharp-determine-os-is-windows-7-or-windows-windows-server-2008

If you want to take a stab at that, a PR is always welcome.

**Comment by jonreis** [comment]
Anjdreas thanks for having a look at this.

I did find a class that seems to be able to determine the version, edition, and service pack of windows (https://www.codeproject.com/Articles/73000/Getting-Operating-System-Version-Info-Even-for-Win).

If I end up using your library, I will add some of the interop calls that are used in the article to return the correct OsVersionInfo

Happy Holidays!
